/* Automatically generated by './src/components/element-ui/bin/generate-entry.js' */
import Vue from 'vue';
import 'element-ui/lib/theme-chalk/aside.css';
import Aside from 'element-ui/lib/aside';
import 'element-ui/lib/theme-chalk/alert.css';
import Alert from 'element-ui/lib/alert';
import 'element-ui/lib/theme-chalk/breadcrumb.css';
import Breadcrumb from 'element-ui/lib/breadcrumb';
import 'element-ui/lib/theme-chalk/breadcrumb-item.css';
import BreadcrumbItem from 'element-ui/lib/breadcrumb-item';
import 'element-ui/lib/theme-chalk/container.css';
import Container from 'element-ui/lib/container';
import 'element-ui/lib/theme-chalk/header.css';
import Header from 'element-ui/lib/header';
import 'element-ui/lib/theme-chalk/loading.css';
import Loading from 'element-ui/lib/loading';
import 'element-ui/lib/theme-chalk/main.css';
import Main from 'element-ui/lib/main';
import 'element-ui/lib/theme-chalk/menu.css';
import Menu from 'element-ui/lib/menu';
import 'element-ui/lib/theme-chalk/menu-item.css';
import MenuItem from 'element-ui/lib/menu-item';
import 'element-ui/lib/theme-chalk/pagination.css';
import Pagination from 'element-ui/lib/pagination';
import 'element-ui/lib/theme-chalk/submenu.css';
import Submenu from 'element-ui/lib/submenu';
import 'element-ui/lib/theme-chalk/table.css';
import Table from 'element-ui/lib/table';
import 'element-ui/lib/theme-chalk/table-column.css';
import TableColumn from 'element-ui/lib/table-column';
import 'element-ui/lib/theme-chalk/tag.css';
import Tag from 'element-ui/lib/tag';

Vue
    .use(Aside)
    .use(Alert)
    .use(Breadcrumb)
    .use(BreadcrumbItem)
    .use(Container)
    .use(Header)
    .use(Loading)
    .use(Main)
    .use(Menu)
    .use(MenuItem)
    .use(Pagination)
    .use(Submenu)
    .use(Table)
    .use(TableColumn)
    .use(Tag);
